# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4665f16b7a28d8cf71da31ae4c342edd"
name = "easy-qr-code"
handle = "easy-qr-code"
application_url = "https://broadband-mitsubishi-follows-pleasure.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "boostprofit.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://broadband-mitsubishi-follows-pleasure.trycloudflare.com/auth/callback",
  "https://broadband-mitsubishi-follows-pleasure.trycloudflare.com/auth/shopify/callback",
  "https://broadband-mitsubishi-follows-pleasure.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
